import { NextRequest, NextResponse } from 'next/server';
import { enqueueVideoPlan } from '@/lib/youtube/approval-store';
import { createVideoPlan } from '@/lib/youtube/video-planner';

function isAuthorized(req: NextRequest) {
  const secret = process.env.CRON_SECRET;
  if (!secret) return process.env.NODE_ENV !== 'production';
  return req.headers.get('authorization') === `Bearer ${secret}`;
}

export async function POST(req: NextRequest) {
  if (!isAuthorized(req)) {
    return NextResponse.json({ ok: false, error: 'Unauthorized' }, { status: 401 });
  }

  const body = await req.json().catch(() => ({}));
  const count = Math.min(Math.max(Number(body.count || 3), 1), 10);
  const items = [];

  for (let i = 0; i < count; i += 1) {
    const plan = await createVideoPlan({
      island: body.island,
      ageBand: body.ageBand,
      topic: Array.isArray(body.topics) ? body.topics[i % body.topics.length] : body.topic,
      musicAssetId: body.musicAssetId,
    });
    items.push(await enqueueVideoPlan(plan, {
      channels: body.channels || ['youtube', 'instagram', 'facebook', 'tiktok'],
      contentType: body.contentType || 'short_lesson',
      durationTarget: body.durationTarget || 'short',
      reviewNotes: 'Generated by twice-daily YouTube growth cron. Requires human approval before publishing.',
    }));
  }

  return NextResponse.json({
    ok: true,
    status: 'queued_for_approval',
    queued: items.length,
    items,
    nextSteps: [
      'Render with Remotion after character and music approval.',
      'Optionally generate motion clips with Seedance provider adapter.',
      'Upload to YouTube as private, made-for-kids, then publish after approval.',
    ],
  });
}
